plugins {
    id 'com.android.application'
}

android {
    namespace 'cz.mushroomfarm.bridge'
    compileSdk 35

    defaultConfig {
        applicationId 'cz.mushroomfarm.bridge.v3'
        minSdk 26
        targetSdk 35
        versionCode 3
        versionName '3.0.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation 'androidx.core:core:1.13.1'
}
